User
petroHutro/graduation pull request #1
Opened 2023-11-21 16:31 UTC by petroHutro

2023-11-26 19:30 UTC, kilchik requested changes

2023-11-26 19:30 UTC, kilchik commented on internal/app/app.go
> +import (
По структуре: выглядит хорошо, только файлики переименуй лучше идиоматично - обсуждали на 1-1

2023-11-26 19:30 UTC, kilchik commented on internal/handlers/handlerEventCreat.go
> +	userID, err := strconv.Atoi(r.Header.Get("User_id"))
Получается, если у меня будет jwt от одного пользователя, а я сделаю запрос на создание ивента и укажу в заголовке другого пользователя - ивент создастся от этого другого пользователя? Это выглядит как огромная дыра в безопасности

2023-11-26 19:30 UTC, kilchik commented on internal/handlers/handlerEventDell.go
> +	if err := st.DellEvent(r.Context(), userID, eventID); err != nil {
И ивент я чужой могу удалить

2023-11-26 19:30 UTC, kilchik commented on internal/handlers/handlersRegister.go
> +	token, _ := authorization.BuildJWTString(secretKey, tokenEXP, id)
Ошибки нельзя игнорировать

2023-11-26 19:30 UTC, kilchik commented on internal/notification/notification.go
> +	tickerGet := time.NewTicker(12 * time.Hour)
Смотри, какая может быть тут проблема. Если ты будешь перезапускать сервис несколько раз в час (например, катить апдейт) или даже несколько раз за 12ч, то каждый раз таймер будет сбрасываться, а значит тикер будет работать не так, как ты ожидаешь. Другими словами, лучше запускать запросы чаще, но убедиться, что селектят и отправляют они не больше, чем ты задумал

2023-11-28 21:33 UTC, petroHutro commented on internal/handlers/handlerEventCreat.go
> +	userID, err := strconv.Atoi(r.Header.Get("User_id"))
В AuthorizationMiddleware реализован процесс извлечения идентификатора из токена JWT, который затем вставляется в заголовок. Если пользователь попытается самостоятельно подставить идентификатор в заголовок, то значения будут просто заменены на те, которые содержатся в токене JWT.

2023-11-28 21:34 UTC, petroHutro commented on internal/handlers/handlerEventDell.go
> +	if err := st.DellEvent(r.Context(), userID, eventID); err != nil {
Благодаря AuthorizationMiddleware, подобные ситуации не возникнут.

2023-11-28 21:35 UTC, petroHutro commented on internal/authorization/authorization.go
> +			} else {
Исправил

2023-11-28 21:35 UTC, petroHutro commented on internal/app/app.go
> +import (
Исправил

2023-11-28 21:35 UTC, petroHutro commented on internal/handlers/handlersRegister.go
> +	token, _ := authorization.BuildJWTString(secretKey, tokenEXP, id)
Исправил

2023-11-28 21:36 UTC, petroHutro commented on internal/notification/notification.go
> +	tickerGet := time.NewTicker(12 * time.Hour)
Исправил

2023-12-04 20:46 UTC, kilchik commented on internal/handlers/handlerEventCreat.go
> +	userID, err := strconv.Atoi(r.Header.Get("User_id"))
Это хитро, но неочевидно. Старайся не прибегать к таким решениям, пч твой код может поддерживать другой человек или ты через месяц (тоже другой человек). Если ты добавишь еще одну мидлварь, которая будет на основе хедеров что-то делать (например, метрики собирать), то такое поведение может оказаться очень неочевидным, и ты потратишь много времени на отладку. Лучше не изменять оригинальный запрос в мидлваре

2023-12-04 21:16 UTC, kilchik requested changes

2023-12-04 21:16 UTC, kilchik commented on internal/storage/event_queries.go
> +	_, err = s.db.ExecContext(ctx, `
Зачем тут три вызова к БД, если можно обойтись одним:
```
DELETE FROM event WHERE id = $1 AND user_id = $2
```

Кроме того лучше сделать удаление файлика и события из базы одной транзакцией - иначе одна операция может пройти успешно, а другая - нет, данные будут несогласованными

2023-12-04 21:16 UTC, kilchik commented on internal/storage/queries.go
> +			_, err = s.db.ExecContext(ctx, `
При инсерте многих записей следует использовать prepared statements

2023-12-04 21:16 UTC, kilchik commented on internal/storage/user_queries.go
> +				return &RepError{Err: fmt.Errorf("cannot SELECT record: %w", err), UniqueViolation: true}
В обоих селектах результат для пользователя ведь будет один и тот же, зачем нам они?

2023-12-04 21:16 UTC, kilchik commented on internal/storage/queries.go
> +		err := send(message.Mail, message.Body, message.Urls)
Отправка писем не должна быть одной из функций метода сущности хранилища. Кроме того представь, что писем нужно разослать очень много, давай здесь предусмотрим рассылку несколькими горутинами

2023-12-05 15:44 UTC, petroHutro commented on internal/app/create_handlers.go
> +			handlers.HandlerLogin(w, r, a.storage, a.conf.TokenSecretKey, a.conf.TokenEXP)
Исправил

2023-12-05 16:21 UTC, petroHutro commented on internal/storage/queries.go
> +			_, err = s.db.ExecContext(ctx, `
Исправил

2023-12-05 17:42 UTC, petroHutro commented on internal/notification/notification.go
> +func SendNotification(st storage.Storage, m *mail.Mail) error {
Исправил

2023-12-05 17:42 UTC, petroHutro commented on internal/notification/notification.go
> +	if err := st.EventsToday(context.Background(), time.Now()); err != nil {
Исправил

2023-12-05 19:50 UTC, petroHutro commented on internal/storage/queries.go
> +		err := send(message.Mail, message.Body, message.Urls)
Исправил

2023-12-05 19:53 UTC, petroHutro commented on internal/storage/user_queries.go
> +				return &RepError{Err: fmt.Errorf("cannot SELECT record: %w", err), UniqueViolation: true}
Эти селекты нужны, чтобы выявить ошибки. Первая ошибка заключается в том, что такого события не существует, а вторая - в том, что данное событие не принадлежит пользователю.

2023-12-05 19:54 UTC, petroHutro commented on internal/storage/event_queries.go
> +	_, err = s.db.ExecContext(ctx, `
Первые два запроса на возможные ошибки. Транзакция добавлена.

2023-12-15 16:55 UTC, merged